import fs from 'node:fs';

const CSV='data/v7_master.csv';
const OUT='audit/PROBLEM_APP_VOCAB_MORPHOLOGY_REGRESSION.json';

function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else quoted=false;}else field+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(field);field='';}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field='';}else field+=c;}if(field.length||row.length){row.push(field.replace(/\r$/,''));rows.push(row);}return rows;}
const toks=s=>[...(String(s??'').replace(/[’‘]/g,"'").toLowerCase().matchAll(/[a-z]+(?:'[a-z]+)?/g))].map(m=>m[0]);
const irregular=new Map(Object.entries({am:'be',is:'be',are:'be',was:'be',were:'be',been:'be',being:'be',has:'have',had:'have',having:'have',does:'do',did:'do',done:'do',doing:'do',goes:'go',went:'go',gone:'go',comes:'come',came:'come',sees:'see',saw:'see',seen:'see',eats:'eat',ate:'eat',eaten:'eat',drinks:'drink',drank:'drink',drunk:'drink',takes:'take',took:'take',taken:'take',makes:'make',made:'make',writes:'write',wrote:'write',written:'write',buys:'buy',bought:'buy',brings:'bring',brought:'bring',thinks:'think',thought:'think',knows:'know',knew:'know',known:'know',speaks:'speak',spoke:'speak',spoken:'speak',tells:'tell',told:'tell',says:'say',said:'say',gets:'get',got:'get',gotten:'get',gives:'give',gave:'give',given:'give',finds:'find',found:'find',leaves:'leave',left:'leave',feels:'feel',felt:'feel',keeps:'keep',kept:'keep',meets:'meet',met:'meet',runs:'run',ran:'run',swims:'swim',swam:'swim',swum:'swim',sits:'sit',sat:'sit',stands:'stand',stood:'stand',loses:'lose',lost:'lose',teaches:'teach',taught:'teach',catches:'catch',caught:'catch',becomes:'become',became:'become',begins:'begin',began:'begin',begun:'begin',builds:'build',built:'build',sends:'send',sent:'send',pays:'pay',paid:'pay',wears:'wear',wore:'wear',worn:'wear',breaks:'break',broke:'break',broken:'break',chooses:'choose',chose:'choose',chosen:'choose',flies:'fly',flew:'fly',flown:'fly',forgets:'forget',forgot:'forget',forgotten:'forget',hears:'hear',heard:'hear',holds:'hold',held:'hold',rides:'ride',rode:'ride',ridden:'ride',sells:'sell',sold:'sell',sleeps:'sleep',slept:'sleep',spends:'spend',spent:'spend',wins:'win',won:'win',children:'child',men:'man',women:'woman',people:'person',mice:'mouse',feet:'foot',teeth:'tooth',better:'good',best:'good',worse:'bad',worst:'bad',farther:'far',farthest:'far',further:'far',furthest:'far'}));
function deriveOnce(t){const out=new Set();if(irregular.has(t))out.add(irregular.get(t));if(t.endsWith("n't")){out.add(t.slice(0,-3));}if(t.includes("'"))out.add(t.split("'")[0]);if(t.length>4&&t.endsWith('ies'))out.add(t.slice(0,-3)+'y');if(t.length>4&&t.endsWith('ves')){out.add(t.slice(0,-3)+'f');out.add(t.slice(0,-3)+'fe');}if(t.length>3&&t.endsWith('es')){out.add(t.slice(0,-2));out.add(t.slice(0,-1));}if(t.length>3&&t.endsWith('s')&&!t.endsWith('ss'))out.add(t.slice(0,-1));if(t.length>4&&t.endsWith('ied'))out.add(t.slice(0,-3)+'y');if(t.length>3&&t.endsWith('ed')){out.add(t.slice(0,-2));out.add(t.slice(0,-1));}if(t.length>5&&t.endsWith('ying'))out.add(t.slice(0,-4)+'ie');if(t.length>4&&t.endsWith('ing')){out.add(t.slice(0,-3));out.add(t.slice(0,-3)+'e');}if(t.length>4&&t.endsWith('ier'))out.add(t.slice(0,-3)+'y');if(t.length>5&&t.endsWith('iest'))out.add(t.slice(0,-4)+'y');if(t.length>3&&t.endsWith('er'))out.add(t.slice(0,-2));if(t.length>4&&t.endsWith('est'))out.add(t.slice(0,-3));for(const x of [...out])if(x.length>3&&x.at(-1)===x.at(-2))out.add(x.slice(0,-1));return [...out];}
function lemmas(t){const seen=new Set([t]);let frontier=[t];for(let depth=0;depth<3;depth++){const next=[];for(const x of frontier)for(const y of deriveOnce(x))if(y&&!seen.has(y)){seen.add(y);next.push(y);}frontier=next;}return [...seen];}
function cls(t){if(irregular.has(t))return 'irregular';if(t.includes("'"))return 'contraction';if(/(iest|est)$/.test(t))return 'superlative';if(/(ier|er)$/.test(t))return 'comparative';if(/ing$/.test(t))return 'ing';if(/(ied|ed)$/.test(t))return 'past_or_participle_regular';if(/(ies|ves|es|s)$/.test(t))return 'plural_or_third_person';return 'other';}

const table=parseCsv(fs.readFileSync(CSV,'utf8').replace(/^\uFEFF/,''));const headers=table[0];const idx=Object.fromEntries(headers.map((h,i)=>[h,i]));for(const h of ['英語','検索用基本形','変化形・別表記'])if(!(h in idx))throw new Error(`missing column ${h}`);
const counts={};const examples={};let variantTokens=0,morphMatched=0;const aliasSamples=[];
for(const r of table.slice(1)){const base=new Set([...toks(r[idx['英語']]),...toks(r[idx['検索用基本形']])]);for(const v of toks(r[idx['変化形・別表記']])){variantTokens++;const c=cls(v);const hit=lemmas(v).find(x=>base.has(x));if(hit&&hit!==v){morphMatched++;counts[c]=(counts[c]||0)+1;(examples[c]??=[]).length<12&&examples[c].push({form:v,base:hit});}else if(!hit&&aliasSamples.length<40)aliasSamples.push(v);}}
const reps={plays:'play',studies:'study',played:'play',studied:'study',playing:'play',making:'make',bigger:'big',biggest:'big',better:'good',best:'good',went:'go',written:'write',"doesn't":'do',children:'child',men:'man',women:'woman',people:'person',mice:'mouse',feet:'foot',teeth:'tooth'};
const representative={};for(const [form,base] of Object.entries(reps))representative[form]={expected:base,candidates:lemmas(form),pass:lemmas(form).includes(base)};
const required=['plays','studies','played','studied','playing','making','bigger','biggest','better','best','went','written',"doesn't",'children','men','women','people','mice','feet','teeth'];
const failures=required.filter(x=>!representative[x].pass);
const result=failures.length?'FAIL':'PASS';
fs.mkdirSync('audit',{recursive:true});fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),source:CSV,result,variant_tokens:variantTokens,morphology_matches_to_same_row_base:morphMatched,class_counts:counts,class_examples:examples,representative_checks:representative,required_failures:failures,alias_or_nonmorph_sample:[...new Set(aliasSamples)].slice(0,40),note:'Checks generic lemma/form normalization used by vocab gating. Non-morph lexical aliases are reported but are not failures.'},null,2)+'\n');
console.log(JSON.stringify({result,variantTokens,morphMatched,counts,failures},null,2));if(failures.length)process.exitCode=1;
