import fs from 'node:fs';
import vm from 'node:vm';
const text=fs.readFileSync('index.html','utf8');
const decl=/\b(?:const|let|var)\s+DATA\s*=\s*/g.exec(text);if(!decl)throw new Error('DATA declaration not found');
let start=decl.index+decl[0].length;while(/\s/.test(text[start]??''))start++;if(text[start]!=='[')throw new Error(`DATA does not start with [ at ${start}`);
function endBracket(src,begin){let d=0,q=null,e=false,lc=false,bc=false;for(let p=begin;p<src.length;p++){const c=src[p],n=src[p+1];if(lc){if(c==='\n')lc=false;continue;}if(bc){if(c==='*'&&n==='/'){bc=false;p++;}continue;}if(q){if(e){e=false;continue;}if(c==='\\'){e=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){lc=true;p++;continue;}if(c==='/'&&n==='*'){bc=true;p++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='[')d++;else if(c===']'){d--;if(d===0)return p;}}return-1;}
const end=endBracket(text,start);if(end<0)throw new Error('DATA closing bracket not found');
const data=vm.runInNewContext(`(${text.slice(start,end+1)})`,Object.create(null),{timeout:5000});if(!Array.isArray(data))throw new Error('DATA not array');
const exam=data.filter(r=>r?.dataset==='exam'), textbook=data.filter(r=>r?.dataset==='textbook');
const freq=(rows,key)=>Object.entries(rows.reduce((a,r)=>{const v=String(r?.[key]??'').trim()||'(blank)';a[v]=(a[v]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]);
const key=s=>String(s??'').toLowerCase().trim().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ');
const by=new Map();for(const r of textbook){const k=key(r.english);if(!k)continue;if(!by.has(k))by.set(k,[]);by.get(k).push(r);}
const recoverable=[],ambiguous=[],unresolved=[];
for(let idx=0;idx<exam.length;idx++){const r=exam[idx],matches=by.get(key(r.english))||[],poses=[...new Set(matches.map(x=>String(x.pos??'').trim()).filter(Boolean))];const base={exam_index:idx,english:r.english,japanese:r.japanese,phrase:r.phrase,exam_category:r.exam_category,exam_subcategory:r.exam_subcategory,match_count:matches.length};if(poses.length===1)recoverable.push({...base,pos:poses[0]});else if(poses.length>1)ambiguous.push({...base,poses});else unresolved.push(base);}
const terms=['品詞','posBox','posMeta','examCategoryBox','examSubBox','filteredRows','state.filters.pos'];const snippets=[];for(const term of terms){let from=0;while(true){const idx=text.indexOf(term,from);if(idx<0)break;snippets.push({term,index:idx,text:text.slice(Math.max(0,idx-1200),Math.min(text.length,idx+2600))});from=idx+term.length;if(snippets.length>=160)break;}}
const report={total_count:data.length,textbook_count:textbook.length,exam_count:exam.length,elementary_count:data.filter(r=>r?.dataset==='elementary').length,exam_pos_blank:exam.filter(r=>!String(r?.pos??'').trim()).length,exam_pos_raw_blank:exam.filter(r=>!String(r?.pos_raw??'').trim()).length,pos_frequency:freq(exam,'pos'),pos_raw_frequency:freq(exam,'pos_raw'),textbook_exact_pos_recoverable_count:recoverable.length,textbook_exact_pos_ambiguous_count:ambiguous.length,manual_or_other_source_needed_count:unresolved.length,recoverable,ambiguous,unresolved,snippet_count:snippets.length};
fs.mkdirSync('audit',{recursive:true});fs.writeFileSync('audit/EXAM_POS_DIAGNOSTIC.json',JSON.stringify(report,null,2)+'\n');fs.writeFileSync('audit/EXAM_POS_UI_SNIPPETS.txt',snippets.map((s,n)=>`===== ${n+1} ${s.term} @ ${s.index} =====\n${s.text}\n`).join('\n'));
const clean=s=>String(s??'').replace(/[\t\r\n]+/g,' ');const rows=[['status','exam_index','english','japanese','phrase','exam_category','candidate_pos'].join('\t')];for(const r of ambiguous)rows.push(['ambiguous',r.exam_index,clean(r.english),clean(r.japanese),r.phrase,clean(r.exam_category),r.poses.join('|')].join('\t'));for(const r of unresolved)rows.push(['unresolved',r.exam_index,clean(r.english),clean(r.japanese),r.phrase,clean(r.exam_category),''].join('\t'));fs.writeFileSync('audit/EXAM_POS_NEEDS_REVIEW.tsv',rows.join('\n')+'\n');
console.log(JSON.stringify({exam_count:exam.length,blank:report.exam_pos_blank,recoverable:recoverable.length,ambiguous:ambiguous.length,unresolved:unresolved.length},null,2));if(exam.length!==534)throw new Error(`exam count changed: ${exam.length}`);
