import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V6.json';let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set(['中2/比較/並びかえ','中3/疑問詞/選択','中3/現在完了形（継続），現在完了進行形/選択','中3/不定詞①，動名詞/選択','中3/接続詞/読解','中3/接続詞/空所補充','中3/仮定法/英作文']);
const comp=[['Tom','Ken','tall','taller'],['Emi','Yuki','young','younger'],['This bag','that bag','heavy','heavier'],['This book','that book','easy','easier'],['My bike','your bike','fast','faster'],['This river','that river','long','longer'],['This box','that box','light','lighter'],['This room','that room','large','larger'],['This question','that question','difficult','more difficult'],['This movie','that movie','interesting','more interesting'],['English','math','popular','more popular'],['This flower','that flower','beautiful','more beautiful'],['Ken','Mike','busy','busier'],['This desk','that desk','small','smaller'],['This street','that street','wide','wider'],['This train','that train','slow','slower']];
const wh=[['Where','When','Why','do you play tennis?','どこで'],['When','Where','Why','do you study English?','いつ'],['Why','When','Where','do you practice every day?','なぜ'],['How','What','Who','do you go to school?','どのように'],['What','Who','Whose','do you want?','何'],['Who','What','Where','helps you at home?','だれが'],['Where','When','Why','does Ken live?','どこに'],['When','Where','Why','does school start?','いつ'],['Why','When','Where','does Emi study English?','なぜ'],['How','What','Who','does Tom come here?','どのように'],['What','Who','Whose','does Yuki need?','何'],['Who','What','Where','uses this computer?','だれが'],['Which','What','Who','book do you want?','どの'],['Whose','Who','Which','bag is this?','だれの']];
const perfect=[['Aya','has worked','here','since April'],['Bob','has lived','in Japan','for two years'],['Ken','has studied','English','since Monday'],['Emi','has known','Yuki','for five years'],['Tom','has used','this computer','since this morning'],['Lucy','has played','tennis','for three years'],['I','have lived','in this town','since 2024'],['We','have studied','English','for two years'],['They','have worked','here','since April'],['You','have known','Ken','for a long time'],['She','has been reading','this book','for an hour'],['He','has been playing','soccer','since noon'],['Aya','has been studying','English','for two hours'],['Tom','has been waiting','for the bus','for twenty minutes'],['Emi','has been using','this computer','since this morning'],['Ken','has been practicing','tennis','for an hour']];
const ger=[['enjoyed','playing tennis','to play tennis','play tennis','Playing tennis'],['enjoyed','reading books','to read books','read books','Reading books'],['finished','cleaning the room','to clean the room','clean the room','Cleaning the room'],['finished','writing the letter','to write the letter','write the letter','Writing the letter'],['started','studying English','to study English','study English','Studying English'],['started','using this computer','to use this computer','use this computer','Using this computer'],['likes','taking pictures','to take pictures','take pictures','Taking pictures'],['likes','listening to music','to listen to music','listen to music','Listening to music']];
const inf=[['wants','to visit Kyoto','visiting Kyoto','visit Kyoto','To visit Kyoto'],['decided','to read this book','reading this book','read this book','To read this book'],['hopes','to see Ken','seeing Ken','see Ken','To see Ken'],['needs','to study English','studying English','study English','To study English'],['tried','to open the door','opening the door','open the door','To open the door'],['plans','to play tennis','playing tennis','play tennis','To play tennis'],['wants','to use this computer','using this computer','use this computer','To use this computer'],['decided','to help his mother','helping his mother','help his mother','To help his mother']];
const names=[['Aya','she','アヤ'],['Bob','he','ボブ'],['Ken','he','ケン'],['Emi','she','エミ'],['Tom','he','トム'],['Lucy','she','ルーシー'],['Mike','he','マイク'],['Yuki','she','ユキ']];
const conjunctionRead=[['because','was tired','stayed home','疲れていたので家にいました'],['because','was hungry','ate lunch','おなかがすいていたので昼食を食べました'],['because','liked books','went to the library','本が好きだったので図書館へ行きました'],['when','came home','started homework','家に帰ったとき宿題を始めました'],['when','arrived at school','met Ken','学校に着いたときケンに会いました'],['before','went to bed','read a book','寝る前に本を読みました'],['after','finished homework','watched TV','宿題を終えたあとテレビを見ました'],['if','is sunny tomorrow','will play tennis','明日晴れならテニスをします']];
const conjunctionFill=[['Call me','you arrive at school','When','〜するとき'],['Call me','you arrive at the library','When','〜するとき'],['I stayed home','I was tired','because','〜なので'],['We will play tennis','it is sunny tomorrow','if','もし〜なら'],['Wash your hands','you eat lunch','before','〜する前に'],['I watched TV','I finished my homework','after','〜したあとで'],['I was reading','Ken came home','when','〜したとき'],['Take an umbrella','it rains','if','もし〜なら']];
const hypoSubjects=[['a bird','鳥'],['a fish','魚'],['a dog','犬'],['a cat','猫'],['a teacher','先生'],['a doctor','医者'],['a chef','料理人'],['a pilot','パイロット'],['a singer','歌手'],['a writer','作家'],['a scientist','科学者'],['a photographer','写真家'],['a musician','音楽家'],['a soccer player','サッカー選手']];
const hypoActions=[['fly in the sky','空を飛べる'],['swim in the sea','海を泳げる'],['run very fast','とても速く走れる'],['jump very high','とても高く跳べる'],['help many students','多くの生徒を助けられる'],['help sick people','病気の人を助けられる'],['cook delicious food','おいしい料理を作れる'],['travel around the world','世界中を旅できる'],['sing for many people','多くの人のために歌える'],['write many books','たくさんの本を書ける'],['study space','宇宙を研究できる'],['take beautiful pictures','きれいな写真を撮れる'],['play music for people','人々のために音楽を演奏できる'],['play in a big stadium','大きなスタジアムでプレーできる']];
const reorder=s=>`( ${s.replace(/[.?]/g,'').split(/\s+/).reverse().join(' / ')} )`;
function build(f,i){
 if(f==='中2/比較/並びかえ'){const p=comp[i%comp.length],s=`${p[0]} is ${p[3]} than ${p[1]}.`;return{q:reorder(s),a:s};}
 if(f==='中3/疑問詞/選択'){const p=wh[i%wh.length];return{q:`( ${p[0]} / ${p[1]} / ${p[2]} ) ${p[3]} 「${p[4]}」に合うものを選びなさい。`,a:p[0]};}
 if(f==='中3/現在完了形（継続），現在完了進行形/選択'){const p=perfect[i%perfect.length];const base=p[1].replace(/^(has|have)\s+/,'');return{q:`${p[0]} ( ${p[1]} / ${base} / is ${base} ) ${p[2]} ${p[3]}. 正しいものを選びなさい。`,a:p[1][0].toUpperCase()+p[1].slice(1)};}
 if(f==='中3/不定詞①，動名詞/選択'){if(i%2===0){const p=ger[Math.floor(i/2)%ger.length],n=names[Math.floor(i/16)%names.length];return{q:`${n[0]} ${p[0]} ( ${p[2]} / ${p[1]} / ${p[3]} ). 正しいものを選びなさい。`,a:p[4]};}const p=inf[Math.floor(i/2)%inf.length],n=names[Math.floor(i/16)%names.length];return{q:`${n[0]} ${p[0]} ( ${p[1]} / ${p[2]} / ${p[3]} ). 正しいものを選びなさい。`,a:p[4]};}
 if(f==='中3/接続詞/読解'){const n=names[i%names.length],p=conjunctionRead[Math.floor(i/names.length)%conjunctionRead.length];let s;if(p[0]==='because')s=`${n[0]} ${p[2]} because ${n[1]} ${p[1]}.`;else if(p[0]==='when')s=`${n[0]} ${p[2]} when ${n[1]} ${p[1]}.`;else if(p[0]==='before')s=`${n[0]} ${p[2]} before ${n[1]} ${p[1]}.`;else if(p[0]==='after')s=`${n[0]} ${p[2]} after ${n[1]} ${p[1]}.`;else s=`${n[0]} ${p[2]} if it ${p[1]}.`;return{q:`${s} 問い：この文の内容として最も適切なものを書きなさい。`,a:`${n[2]}は${p[3]}。`};}
 if(f==='中3/接続詞/空所補充'){const p=conjunctionFill[i%conjunctionFill.length];return{q:`${p[0]} (      ) ${p[1]}. 「${p[3]}」に合う語を書きなさい。`,a:p[2][0].toUpperCase()+p[2].slice(1)};}
 if(f==='中3/仮定法/英作文'){const s=hypoSubjects[i%hypoSubjects.length],a=hypoActions[Math.floor(i/hypoSubjects.length)%hypoActions.length];return{q:`次の日本語に合う英文を書きなさい。『もし私が${s[1]}なら、${a[1]}のに。』`,a:`If I were ${s[0]}, I could ${a[0]}.`};}
 return null;}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<10000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<120)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
