import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V2.json';
let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];
const by=new Map();for(const x of rows){const k=key(x),a=by.get(k)||[];a.push(x);by.set(k,a);}const used=new Set(rows.map(key));
const targets=new Set(['中3/分詞と間接疑問文/選択','中3/分詞と間接疑問文/間違い直し','中3/分詞と間接疑問文/英作文','中3/関係代名詞/選択','中3/関係代名詞/間違い直し','中3/関係代名詞/並びかえ','中3/比較/英作文','中3/命令文，there is ～ の文/読解','中3/文型/見分け']);
const indirect=[['where Tom lives','where does Tom live','トムがどこに住んでいるか'],['when school starts','when does school start','学校がいつ始まるか'],['why Emi studies English','why does Emi study English','エミがなぜ英語を勉強するか'],['how Ken goes to school','how does Ken go to school','ケンがどのように学校へ行くか'],['what Mike wants','what does Mike want','マイクが何をほしがっているか'],['where Aya plays tennis','where does Aya play tennis','アヤがどこでテニスをするか'],['when they come here','when do they come here','彼らがいつここへ来るか'],['why Yuki is busy','why is Yuki busy','ユキがなぜ忙しいか']];
const relatives=[['The boy','plays soccer','is my friend'],['The girl','studies English','is kind'],['The man','works here','is Mr. Brown'],['The woman','teaches us English','is kind'],['The student','reads many books','is Ken'],['The teacher','lives near school','is friendly'],['The player','runs fast','is Tom'],['The girl','uses this computer','is Emi']];
const comps=[['This bag','that one','big','bigger','このかばんはあのかばんより大きいです。'],['This book','that one','easy','easier','この本はあの本より簡単です。'],['Tom','Ken','tall','taller','トムはケンより背が高いです。'],['Emi','Yuki','young','younger','エミはユキより若いです。'],['This river','that river','long','longer','この川はあの川より長いです。'],['My bike','your bike','fast','faster','私の自転車はあなたの自転車より速いです。'],['This box','that one','light','lighter','この箱はあの箱より軽いです。'],['This room','that one','large','larger','この部屋はあの部屋より広いです。']];
const commands=[['Open the door, please.','ドアを開けてください。'],['Close the window, please.','窓を閉めてください。'],['Please sit down.','座ってください。'],['Please be quiet.','静かにしてください。'],['Look at this picture.','この写真を見なさい。'],['Read this book, please.','この本を読んでください。'],['Please come here.','ここへ来てください。'],['Do not run here.','ここで走ってはいけません。'],['There is a book on the desk.','机の上に本があります。'],['There are two students in the room.','部屋に生徒が2人います。']];
const patterns=[['They call him Ken.','AをBと呼ぶ文'],['We call her Emi.','AをBと呼ぶ文'],['My friends call me Mike.','AをBと呼ぶ文'],['She gave me a book.','人に物を与える文'],['Tom showed us a picture.','人に物を与える文'],['My mother made me lunch.','人に物を与える文'],['Ken sent Emi a letter.','人に物を与える文'],['They named the dog Pochi.','AをBと呼ぶ文']];
const scramble=s=>{const w=s.replace(/[.?]/g,'').split(/\s+/);const o=[];for(let i=1;i<w.length;i+=2)o.push(w[i]);for(let i=0;i<w.length;i+=2)o.push(w[i]);return o.join(' / ')};
function build(f,i){
 if(f.startsWith('中3/分詞と間接疑問文/')){const p=indirect[i%indirect.length];if(f.endsWith('/選択'))return{q:`I don't know (A) ${p[1]} (B) ${p[0]} (C) ${p[0].split(' ').reverse().join(' ')}. 正しいものを選びなさい。`,a:'B'};if(f.endsWith('/間違い直し'))return{q:`I don't know ${p[1]}. の誤りを直しなさい。`,a:`I don't know ${p[0]}.`};return{q:`「私は${p[2]}知りません。」を英語にしなさい。`,a:`I don't know ${p[0]}.`};}
 if(f.startsWith('中3/関係代名詞/')){const p=relatives[i%relatives.length],good=`${p[0]} who ${p[1]} ${p[2]}.`,bad=`${p[0]} which ${p[1]} ${p[2]}.`;if(f.endsWith('/選択'))return{q:`${p[0]} ( who / which / where ) ${p[1]} ${p[2]}. 正しいものを選びなさい。`,a:'who'};if(f.endsWith('/間違い直し'))return{q:`${bad} の誤りを、who を使って直しなさい。`,a:good};return{q:`次の語(句)を正しい順に並べかえなさい。 ( ${scramble(good)} )`,a:good};}
 if(f==='中3/比較/英作文'){const p=comps[i%comps.length];return{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} is ${p[3]} than ${p[1]}.`};}
 if(f==='中3/命令文，there is ～ の文/読解'){const p=commands[i%commands.length];return{q:`${p[0]} 問い：この英文の意味として最も適切なものを書きなさい。`,a:p[1]};}
 if(f==='中3/文型/見分け'){const p=patterns[i%patterns.length];return{q:`${p[0]} は『人に物を与える文』か、『AをBと呼ぶ文』か答えなさい。`,a:p[1]};}
 return null;}
const idx={},stats={groups_eligible:0,changed_rows:0,groups_touched:0,by_family:{},samples:[]};
for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<1000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<60)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const k=key(x),a=after.get(k)||[];a.push(x);after.set(k,a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');
const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
