import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V9.json';let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set(['中3/人称代名詞/間違い直し','中3/文型/間違い直し','中2/比較/英作文','中3/文型/英作文','中3/命令文，there is ～ の文/英作文','中3/現在完了形（継続），現在完了進行形/英作文']);
const pron=[['Me play soccer.','I play soccer.'],['Him studies English.','He studies English.'],['Her likes music.','She likes music.'],['Us go to school.','We go to school.'],['Them play tennis.','They play tennis.'],['Me read books.','I read books.'],['Him runs every day.','He runs every day.'],['Her studies math.','She studies math.']];
const call=[['Tom','him'],['Ken','him'],['Mike','him'],['Bob','him'],['John','him'],['Emi','her'],['Yuki','her'],['Aya','her'],['Lucy','her'],['Mary','her'],['Ann','her'],['Kate','her']];
const comp=[['トムはケンより背が高い。','Tom is taller than Ken.'],['このかばんはあのかばんより大きい。','This bag is larger than that one.'],['この問題はあの問題よりやさしい。','This question is easier than that one.'],['この自転車はあの自転車より速い。','This bike is faster than that one.'],['この花はあの花より美しい。','This flower is more beautiful than that one.'],['英語は数学より人気があります。','English is more popular than math.'],['ケンはマイクより忙しい。','Ken is busier than Mike.'],['この本はあの本よりおもしろい。','This book is more interesting than that one.']];
const make=[['その知らせで私はうれしくなりました。','The news made me happy.'],['その映画で彼女は悲しくなりました。','The movie made her sad.'],['その練習で彼は強くなりました。','The practice made him strong.'],['その話で私たちは幸せになりました。','The story made us happy.'],['その音で赤ちゃんは目を覚ましました。','The sound made the baby awake.'],['その仕事で彼は忙しくなりました。','The work made him busy.']];
const imp=[['教室では走らないでください。','Do not run in the classroom.'],['ここでは写真を撮らないでください。','Do not take pictures here.'],['窓を開けてください。','Please open the window.'],['静かにしてください。','Please be quiet.'],['このドアを開けないでください。','Do not open this door.'],['ここに座ってください。','Please sit here.'],['その本を読んでください。','Please read that book.'],['遅れないでください。','Do not be late.']];
const perf=[['月曜日からずっとこの町に住んでいます。','I have lived in this town since Monday.'],['火曜日からずっとこの町に住んでいます。','I have lived in this town since Tuesday.'],['水曜日からずっとこの町に住んでいます。','I have lived in this town since Wednesday.'],['木曜日からずっとこの町に住んでいます。','I have lived in this town since Thursday.'],['金曜日からずっとこの町に住んでいます。','I have lived in this town since Friday.'],['3年間ずっとこの町に住んでいます。','I have lived in this town for three years.'],['5年間ずっとこの町に住んでいます。','I have lived in this town for five years.']];
function build(f,i){if(f==='中3/人称代名詞/間違い直し'){const p=pron[i%pron.length];return{q:`${p[0]} の誤りを直しなさい。`,a:p[1]};}if(f==='中3/文型/間違い直し'){const p=call[i%call.length];return{q:`They call ${p[0]} ${p[1]}. の誤りを直しなさい。`,a:`They call ${p[1]} ${p[0]}.`};}if(f==='中2/比較/英作文'){const p=comp[i%comp.length];return{q:`次の日本語に合う英文を書きなさい。『${p[0]}』`,a:p[1]};}if(f==='中3/文型/英作文'){const p=make[i%make.length];return{q:`次の日本語に合う英文を書きなさい。『${p[0]}』`,a:p[1]};}if(f==='中3/命令文，there is ～ の文/英作文'){const p=imp[i%imp.length];return{q:`次の日本語に合う英文を書きなさい。『${p[0]}』`,a:p[1]};}if(f==='中3/現在完了形（継続），現在完了進行形/英作文'){const p=perf[i%perf.length];return{q:`次の日本語に合う英文を書きなさい。『私は${p[0]}』`,a:p[1]};}return null;}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<10000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<100)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));