import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V5.json';
let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');
const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];
const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set([
'中3/仮定法/英作文','中3/命令文，there is ～ の文/読解','中3/文型/見分け','中3/受動態/空所補充','中3/比較/英作文','中3/現在完了形（継続），現在完了進行形/英作文','中3/分詞と間接疑問文/英作文','中3/不定詞①，動名詞/並びかえ'
]);
const hypo=[['a bird','fly in the sky','鳥','空を飛べる'],['a fish','swim in the sea','魚','海を泳げる'],['a doctor','help sick people','医者','病気の人を助けられる'],['a chef','cook delicious food','料理人','おいしい料理を作れる'],['a pilot','fly around the world','パイロット','世界中を飛べる'],['a singer','sing for many people','歌手','多くの人のために歌える'],['a writer','write many books','作家','たくさんの本を書ける'],['a scientist','study space','科学者','宇宙を研究できる'],['a soccer player','play in a big stadium','サッカー選手','大きなスタジアムでプレーできる'],['a photographer','take many pictures','写真家','たくさん写真を撮れる'],['a teacher','teach English','先生','英語を教えられる'],['a musician','play music for people','音楽家','人々のために音楽を演奏できる']];
const commands=[['Please close the window.','窓を閉めてください。'],['Please sit down.','座ってください。'],['Please be quiet.','静かにしてください。'],['Please read this book.','この本を読んでください。'],['Please come here.','ここへ来てください。'],['Don’t touch this box.','この箱に触らないでください。'],['Don’t use this computer.','このコンピューターを使わないでください。'],['Don’t eat here.','ここで食べないでください。'],['There is a pen on the desk.','机の上にペンが1本あります。'],['There are three books in the bag.','かばんの中に本が3冊あります。'],['There is a cat under the chair.','いすの下に猫が1匹います。'],['There are two students by the door.','ドアのそばに生徒が2人います。']];
const patterns=[['They call him Mike.','AをBと呼ぶ文'],['We call her Yuki.','AをBと呼ぶ文'],['My friends call me Ken.','AをBと呼ぶ文'],['They named the dog Pochi.','AをBと呼ぶ文'],['She gave me a notebook.','人に物を与える文'],['Tom showed us a picture.','人に物を与える文'],['My mother made me lunch.','人に物を与える文'],['Ken sent Emi a letter.','人に物を与える文'],['Mr. Brown taught us English.','人に物を与える文'],['Aya bought her brother a book.','人に物を与える文'],['We call the cat Tama.','AをBと呼ぶ文'],['They named the baby Ken.','AをBと呼ぶ文']];
const passive=[['This computer','use','Used','by many students'],['English','speak','Spoken','in many countries'],['This room','clean','Cleaned','every day'],['These pictures','take','Taken','in Kyoto'],['This book','write','Written','in English'],['Lunch','make','Made','by my mother'],['The window','open','Opened','every morning'],['The letters','send','Sent','every week'],['This song','sing','Sung','by many students'],['The bike','use','Used','by Ken'],['The door','close','Closed','at five'],['Rice','eat','Eaten','in many countries']];
const comps=[['This game','the three games','easy','easiest','このゲームは3つのゲームの中でいちばん簡単です。'],['This river','the three rivers','long','longest','この川は3本の川の中でいちばん長いです。'],['My bike','the three bikes','fast','fastest','私の自転車は3台の中でいちばん速いです。'],['This box','the three boxes','light','lightest','この箱は3つの箱の中でいちばん軽いです。'],['This book','the three books','easy','easiest','この本は3冊の中でいちばん簡単です。'],['Tom','the three boys','tall','tallest','トムは3人の男の子の中でいちばん背が高いです。'],['Emi','the three girls','young','youngest','エミは3人の女の子の中でいちばん若いです。'],['This room','the three rooms','large','largest','この部屋は3つの部屋の中でいちばん広いです。'],['Tom','Ken','tall','taller','トムはケンより背が高いです。'],['Emi','Yuki','young','younger','エミはユキより若いです。'],['This room','that room','large','larger','この部屋はあの部屋より広いです。'],['My bag','your bag','heavy','heavier','私のかばんはあなたのかばんより重いです。']];
const perfectComp=[['I','have lived','in this town','since Sunday','私は日曜日からずっとこの町に住んでいます。'],['I','have studied','English','for three years','私は3年間ずっと英語を勉強しています。'],['We','have lived','in this city','for five years','私たちは5年間ずっとこの市に住んでいます。'],['They','have known','Ken','since April','彼らは4月からずっとケンを知っています。'],['She','has studied','English','since this morning','彼女は今朝からずっと英語を勉強しています。'],['He','has lived','in Japan','for two years','彼は2年間ずっと日本に住んでいます。'],['I','have been reading','this book','for an hour','私は1時間ずっとこの本を読んでいます。'],['We','have been practicing','tennis','since noon','私たちは正午からずっとテニスを練習しています。'],['They','have been waiting','for the bus','for twenty minutes','彼らは20分間ずっとバスを待っています。'],['She','has been using','this computer','since this morning','彼女は今朝からずっとこのコンピューターを使っています。'],['He','has been playing','soccer','for two hours','彼は2時間ずっとサッカーをしています。'],['I','have been writing','a letter','for thirty minutes','私は30分間ずっと手紙を書いています。']];
const indirect=[['where Tom lives','トムがどこに住んでいるのか'],['when school starts','学校がいつ始まるのか'],['why Emi studies English','エミがなぜ英語を勉強するのか'],['how Ken goes to school','ケンがどのように学校へ行くのか'],['what Mike wants','マイクが何をほしがっているのか'],['where Aya plays tennis','アヤがどこでテニスをするのか'],['when they come here','彼らがいつここへ来るのか'],['why Yuki is busy','ユキがなぜ忙しいのか'],['how Emi uses this computer','エミがどのようにこのコンピューターを使うのか'],['what Ken needs','ケンに何が必要なのか'],['where Mr. Brown works','ブラウン先生がどこで働いているのか'],['when Tom practices soccer','トムがいつサッカーを練習するのか']];
const infinitive=[['English is fun to learn.'],['This book is easy to read.'],['This question is difficult to answer.'],['It is important to study every day.'],['I want to visit Kyoto.'],['She likes reading books.'],['He enjoys playing soccer.'],['We started studying English.'],['My hobby is taking pictures.'],['To help others is important.'],['I decided to read this book.'],['They finished cleaning the room.']];
const scramble=s=>{const w=s.replace(/[.?]/g,'').split(/\s+/),o=[];for(let i=1;i<w.length;i+=2)o.push(w[i]);for(let i=0;i<w.length;i+=2)o.push(w[i]);return o.join(' / ')};
function build(f,i){
 if(f==='中3/仮定法/英作文'){const p=hypo[i%hypo.length];return{q:`次の日本語に合う英文を書きなさい。『もし私が${p[2]}なら、${p[3]}のに。』`,a:`If I were ${p[0]}, I could ${p[1]}.`};}
 if(f==='中3/命令文，there is ～ の文/読解'){const p=commands[i%commands.length];return{q:`${p[0]} 問い：この英文の意味として最も適切なものを書きなさい。`,a:p[1]};}
 if(f==='中3/文型/見分け'){const p=patterns[i%patterns.length];return{q:`${p[0]} は『人に物を与える文』か、『AをBと呼ぶ文』か答えなさい。`,a:p[1]};}
 if(f==='中3/受動態/空所補充'){const p=passive[i%passive.length];const be=/^(These|The letters)\b/.test(p[0])?'are':'is';return{q:`${p[0]} ${be} (      ) ${p[3]}. (${p[1]}) の（ ）内を正しくしなさい。`,a:p[2]};}
 if(f==='中3/比較/英作文'){const p=comps[i%comps.length],superlative=/the three/.test(p[1]);return superlative?{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} is the ${p[3]} of ${p[1]}.`}:{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} is ${p[3]} than ${p[1]}.`};}
 if(f==='中3/現在完了形（継続），現在完了進行形/英作文'){const p=perfectComp[i%perfectComp.length];return{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} ${p[1]} ${p[2]} ${p[3]}.`};}
 if(f==='中3/分詞と間接疑問文/英作文'){const p=indirect[i%indirect.length];return{q:`次の日本語に合う英文を書きなさい。『私は${p[1]}わかりません。』`,a:`I don't know ${p[0]}.`};}
 if(f==='中3/不定詞①，動名詞/並びかえ'){const s=infinitive[i%infinitive.length][0];return{q:`次の語(句)を正しい順に並べかえなさい。 ( ${scramble(s)} )`,a:s};}
 return null;
}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};
for(const g of by.values()){
 if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;
 for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<4000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<120)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}
 if(touched)stats.groups_touched++;
}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;
if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');
const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
