import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V7.json';let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set(['中3/現在完了形（完了・経験）/変形','中3/現在完了形（継続），現在完了進行形/変形','中1/三単現/間違い直し','中3/現在完了形（完了・経験）/空所補充','中3/疑問詞/答え方','中1/be動詞/答え方','中3/人称代名詞/間違い直し']);
const people=[['Tom','he'],['Ken','he'],['Mike','he'],['Bob','he'],['John','he'],['Emi','she'],['Yuki','she'],['Aya','she'],['Lucy','she'],['Mary','she'],['Ann','she'],['Kate','she']];
const places=['Kyoto','Osaka','Tokyo','the museum','the zoo','the library','the park','Hiroshima','Nara','Fukuoka','Kobe','Nagoya'];
const cont=[['been studying English','for two hours'],['been reading this book','for an hour'],['been using this computer','since this morning'],['been waiting for the bus','for twenty minutes'],['been playing soccer','for an hour'],['been playing tennis','for two hours'],['been practicing English','since noon'],['been cleaning the room','for thirty minutes'],['been cooking dinner','for an hour'],['been working here','since Monday'],['lived in this town','for three years'],['known Ken','for five years']];
const actions=[['play soccer','plays soccer'],['study English','studies English'],['read books','reads books'],['help at home','helps at home'],['walk to school','walks to school'],['play tennis','plays tennis'],['use a computer','uses a computer'],['listen to music','listens to music'],['clean the room','cleans the room'],['wash the dishes','washes the dishes'],['cook dinner','cooks dinner'],['visit the library','visits the library']];
const parts=[['finish','Finished','my homework'],['write','Written','the letter'],['eat','Eaten','lunch'],['see','Seen','that movie'],['do','Done','the work'],['take','Taken','many pictures'],['read','Read','this book'],['make','Made','lunch'],['buy','Bought','this bag'],['speak','Spoken','English'],['come','Come','here'],['know','Known','Ken']];
const whAns=[['I went to the library by bus.','How did you go to the library?'],['I went to the park on foot.','How did you go to the park?'],['I went to the station by train.','How did you go to the station?'],['I went to school by bike.','How did you go to school?'],['I studied English yesterday.','What did you study yesterday?'],['I played tennis after school.','What did you play after school?'],['I met Ken at the library.','Where did you meet Ken?'],['I saw Tom at the station.','Where did you see Tom?'],['I got up at seven.','When did you get up?'],['I came home at six.','When did you come home?'],['I went there because I wanted a book.','Why did you go there?'],['Ken helped me at home.','Who helped you at home?']];
const adj=[['busy','忙しい'],['kind','親切な'],['happy','うれしい'],['tired','疲れている'],['hungry','おなかがすいている'],['free','ひまな'],['ready','準備ができている'],['fine','元気な'],['young','若い'],['quiet','静かな'],['careful','注意深い'],['friendly','親しみやすい']];
const wrongPron=[['Me','I','play soccer'],['Him','He','studies English'],['Her','She','plays tennis'],['Them','They','read books'],['Us','We','use this computer'],['Me','I','go running'],['Him','He','plays soccer'],['Her','She','studies English'],['Them','They','play tennis'],['Us','We','listen to music'],['Me','I','go swimming'],['Him','He','helps at home']];
function pron(s,p){return p;}
function build(f,i){
 const pe=people[i%people.length];
 if(f==='中3/現在完了形（完了・経験）/変形'){const pl=places[Math.floor(i/people.length)%places.length],decl=`${pe[0]} has been to ${pl} once.`;if(i%2===0)return{q:`${decl} を疑問文にしなさい。`,a:`Has ${pe[0]} been to ${pl} once?`};return{q:`${decl} を否定文にしなさい。`,a:`${pe[0]} has not been to ${pl} once.`};}
 if(f==='中3/現在完了形（継続），現在完了進行形/変形'){const p=cont[Math.floor(i/people.length)%cont.length],decl=`${pe[0]} has ${p[0]} ${p[1]}.`;if(i%2===0)return{q:`${decl} を疑問文にしなさい。`,a:`Has ${pe[0]} ${p[0]} ${p[1]}?`};return{q:`${decl} を否定文にしなさい。`,a:`${pe[0]} has not ${p[0]} ${p[1]}.`};}
 if(f==='中1/三単現/間違い直し'){const a=actions[i%actions.length],s=people[Math.floor(i/actions.length)%people.length][0];return{q:`${s} ${a[0]} every day. の誤りを直しなさい。`,a:`${s} ${a[1]} every day.`};}
 if(f==='中3/現在完了形（完了・経験）/空所補充'){const p=parts[i%parts.length];return{q:`I have just (      ) ${p[2]}. (${p[0]}) の（ ）内を正しくしなさい。`,a:p[1]};}
 if(f==='中3/疑問詞/答え方'){const p=whAns[i%whAns.length];return{q:`${p[0]} になる質問文を書きなさい。`,a:p[1]};}
 if(f==='中1/be動詞/答え方'){const a=adj[Math.floor(i/people.length)%adj.length],yes=i%2===0,p=pe[1];return{q:`Is ${p} ${a[0]}? に ${yes?'Yes':'No'} で答えなさい。`,a:`${yes?'Yes':'No'}, ${p} ${yes?'is':'is not'}.`};}
 if(f==='中3/人称代名詞/間違い直し'){const p=wrongPron[i%wrongPron.length];return{q:`${p[0]} ${p[2]}. の誤りを直しなさい。`,a:`${p[1]} ${p[2]}.`};}
 return null;}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<10000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<120)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
