import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V4.json';let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set(['中3/現在完了形（継続），現在完了進行形/間違い直し','中3/現在完了形（継続），現在完了進行形/空所補充','中3/分詞と間接疑問文/選択','中3/分詞と間接疑問文/間違い直し','中3/現在完了形（完了・経験）/空所補充','中3/人称代名詞/選択','中3/人称代名詞/間違い直し','中3/比較/英作文']);
const periods=[['two years','for'],['three years','for'],['five years','for'],['a week','for'],['two months','for'],['a long time','for'],['Monday','since'],['last year','since'],['this morning','since'],['April','since'],['2024','since'],['I was ten','since']];
const indirect=[['where Tom lives','where does Tom live'],['when Emi comes here','when does Emi come here'],['why Ken studies English','why does Ken study English'],['how Yuki goes to school','how does Yuki go to school'],['what Mike wants','what does Mike want'],['where Aya plays tennis','where does Aya play tennis'],['when school starts','when does school start'],['why Tom is busy','why is Tom busy'],['how Emi uses this computer','how does Emi use this computer'],['what Ken needs','what does Ken need']];
const participles=[['finish','Finished','my homework'],['write','Written','the letter'],['eat','Eaten','lunch'],['see','Seen','that movie'],['do','Done','the work'],['take','Taken','many pictures'],['read','Read','this book'],['make','Made','lunch'],['buy','Bought','this bag'],['speak','Spoken','English']];
const pron=[['She','Her','Hers','plays tennis'],['He','Him','His','studies English'],['They','Them','Theirs','play soccer'],['We','Us','Ours','read books'],['I','Me','Mine','use this computer']];
const objPron=[['she','her','hers','I talked with'],['he','him','his','I helped'],['they','them','theirs','I know'],['we','us','ours','Tom spoke to'],['I','me','mine','Ken called']];
const wrongPron=[['Me','I','play soccer'],['Him','He','studies English'],['Her','She','plays tennis'],['Them','They','read books'],['Us','We','use this computer']];
const comps=[['This game','the three games','easy','easiest','このゲームは3つのゲームの中でいちばん簡単です。'],['Tom','the three boys','kind','kindest','トムは3人の男の子の中でいちばん親切です。'],['This river','the three rivers','long','longest','この川は3本の川の中でいちばん長いです。'],['My bike','the three bikes','fast','fastest','私の自転車は3台の中でいちばん速いです。'],['This box','the three boxes','light','lightest','この箱は3つの箱の中でいちばん軽いです。'],['This book','the three books','easy','easiest','この本は3冊の中でいちばん簡単です。'],['Tom','Ken','tall','taller','トムはケンより背が高いです。'],['Emi','Yuki','young','younger','エミはユキより若いです。'],['This room','that room','large','larger','この部屋はあの部屋より広いです。'],['My bag','your bag','heavy','heavier','私のかばんはあなたのかばんより重いです。']];
function build(f,i){
 if(f==='中3/現在完了形（継続），現在完了進行形/間違い直し'){const p=periods[i%periods.length],wrong=p[1]==='for'?'since':'for';return{q:`He has lived in Japan ${wrong} ${p[0]}. の誤りを直しなさい。`,a:`He has lived in Japan ${p[1]} ${p[0]}.`};}
 if(f==='中3/現在完了形（継続），現在完了進行形/空所補充'){const p=periods[i%periods.length];return{q:`I have studied English (      ) ${p[0]}. 空所に入る最も適切な語を書きなさい。`,a:p[1][0].toUpperCase()+p[1].slice(1)};}
 if(f==='中3/分詞と間接疑問文/選択'){const p=indirect[i%indirect.length];return{q:`I don't know (A) ${p[1]} (B) ${p[0]} (C) ${p[0].split(' ').reverse().join(' ')}. 正しいものを選びなさい。`,a:'B'};}
 if(f==='中3/分詞と間接疑問文/間違い直し'){const p=indirect[i%indirect.length];return{q:`I don't know ${p[1]}. の誤りを直しなさい。`,a:`I don't know ${p[0]}.`};}
 if(f==='中3/現在完了形（完了・経験）/空所補充'){const p=participles[i%participles.length];return{q:`I have just (      ) ${p[2]}. (${p[0]}) の（ ）内を正しくしなさい。`,a:p[1]};}
 if(f==='中3/人称代名詞/選択'){if(i%2===0){const p=pron[Math.floor(i/2)%pron.length];return{q:`( ${p[0]} / ${p[1]} / ${p[2]} ) ${p[3]}. 正しいものを選びなさい。`,a:p[0]};}const p=objPron[Math.floor(i/2)%objPron.length];return{q:`${p[3]} ( ${p[0]} / ${p[1]} / ${p[2]} ). 正しいものを選びなさい。`,a:p[1][0].toUpperCase()+p[1].slice(1)};}
 if(f==='中3/人称代名詞/間違い直し'){const p=wrongPron[i%wrongPron.length];return{q:`${p[0]} ${p[2]}. の誤りを直しなさい。`,a:`${p[1]} ${p[2]}.`};}
 if(f==='中3/比較/英作文'){const p=comps[i%comps.length];const superlative=/the three/.test(p[1]);return superlative?{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} is the ${p[3]} of ${p[1]}.`}:{q:`次の日本語に合う英文を書きなさい。『${p[4]}』`,a:`${p[0]} is ${p[3]} than ${p[1]}.`};}
 return null;}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<3000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<100)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
