import fs from 'node:fs';
const HTML='problem-app/index.html',OUT='audit/PROBLEM_APP_HIGH_CONFIDENCE_DUPLICATE_DIVERSIFICATION_V8.json';let html=fs.readFileSync(HTML,'utf8');const re=/<script\s+id=["']qb-data["'][^>]*>([\s\S]*?)<\/script>/i,m=re.exec(html);if(!m)throw Error('qb-data');const all=JSON.parse(m[1]),rows=all.filter(x=>x?.subject==='英語');
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase(),key=x=>norm(x.q)+'\u0000'+norm(x.a),fam=x=>`${x.grade}/${x.category}/${x.type}`,pref=x=>String(x.id||'').split('-')[0];const by=new Map();for(const x of rows){const a=by.get(key(x))||[];a.push(x);by.set(key(x),a);}const used=new Set(rows.map(key));
const targets=new Set(['中3/文型/間違い直し','中3/助動詞/変形','中3/関係代名詞/選択','中3/関係代名詞/間違い直し','中2/助動詞/英作文','中2/比較/英作文']);
const names=[['Tom','him'],['Ken','him'],['Mike','him'],['Bob','him'],['John','him'],['Emi','her'],['Yuki','her'],['Aya','her'],['Lucy','her'],['Mary','her'],['Ann','her'],['Kate','her']];
const places=['the library','the park','the station','school','the museum','the zoo','the room','the store','the hospital','the office','the gym','the garden'];
const rel=[['The book','Kate','used','which'],['The bag','Mary','bought','which'],['The bike','Ken','uses','which'],['The computer','Tom','fixed','which'],['The picture','Emi','took','which'],['The boy','plays soccer','is my friend','who'],['The girl','studies English','is kind','who'],['The man','works here','is Mr. Brown','who'],['The woman','teaches us English','is kind','who'],['The student','reads many books','is Ken','who']];
const mod=[['早く起きなければならない','have to get up early'],['遅れてはいけない','must not be late'],['この部屋を掃除しなければならない','have to clean this room'],['ここで走ってはいけない','must not run here'],['今日宿題をしなければならない','have to do your homework today'],['この本を読まなければならない','have to read this book'],['今出発しなければならない','must leave now'],['静かにしなければならない','must be quiet'],['明日学校へ行かなければならない','have to go to school tomorrow'],['このドアを開けてはいけない','must not open this door']];
const comp=[['エミ','ユキ','若い','Emi is younger than Yuki.'],['トム','ケン','背が高い','Tom is taller than Ken.'],['このかばん','あのかばん','大きい','This bag is larger than that one.'],['この問題','あの問題','やさしい','This question is easier than that one.'],['この川','あの川','長い','This river is longer than that one.'],['この自転車','あの自転車','速い','This bike is faster than that one.'],['この箱','あの箱','軽い','This box is lighter than that one.'],['この部屋','あの部屋','広い','This room is larger than that one.'],['この映画','あの映画','わくわくする','This movie is more exciting than that movie.'],['英語','数学','人気がある','English is more popular than math.'],['この花','あの花','美しい','This flower is more beautiful than that one.'],['ケン','マイク','忙しい','Ken is busier than Mike.']];
function build(f,i){if(f==='中3/文型/間違い直し'){const n=names[i%names.length];return{q:`They call ${n[0]} ${n[1]}. の誤りを直しなさい。`,a:`They call ${n[1]} ${n[0]}.`};}if(f==='中3/助動詞/変形'){const p=places[i%places.length],decl=`You must go to ${p} now.`;return i%2===0?{q:`${decl} を疑問文にしなさい。`,a:`Must you go to ${p} now?`}:{q:`${decl} を否定文にしなさい。`,a:`You must not go to ${p} now.`};}if(f==='中3/関係代名詞/選択'){const p=rel[i%rel.length];if(p[3]==='which')return{q:`${p[0]} ( who / which / where ) ${p[1]} ${p[2]} yesterday is mine. 正しいものを選びなさい。`,a:'which'};return{q:`${p[0]} ( who / which / where ) ${p[1]} ${p[2]}. 正しいものを選びなさい。`,a:'who'};}if(f==='中3/関係代名詞/間違い直し'){const p=rel[(i+5)%rel.length];if(p[3]==='who'){const good=`${p[0]} who ${p[1]} ${p[2]}.`;return{q:`${p[0]} which ${p[1]} ${p[2]}. の誤りを、who を使って直しなさい。`,a:good};}const good=`${p[0]} which ${p[1]} ${p[2]} yesterday is mine.`;return{q:`${p[0]} who ${p[1]} ${p[2]} yesterday is mine. の誤りを、which を使って直しなさい。`,a:good};}if(f==='中2/助動詞/英作文'){const p=mod[i%mod.length];return{q:`次の日本語に合う英文を書きなさい。『あなたは${p[0]}。』`,a:`You ${p[1]}.`};}if(f==='中2/比較/英作文'){const p=comp[i%comp.length];return{q:`次の日本語に合う英文を書きなさい。『${p[0]}は${p[1]}より${p[2]}。』`,a:p[3]};}return null;}
const idx={},stats={groups_eligible:0,groups_touched:0,changed_rows:0,by_family:{},samples:[]};for(const g of by.values()){if(g.length<2||g.length>4)continue;const f=fam(g[0]);if(!targets.has(f)||!g.every(x=>fam(x)===f&&pref(x)===pref(g[0])))continue;stats.groups_eligible++;let touched=false;for(let j=1;j<g.length;j++){const x=g[j];let i=idx[f]||0,out=null,k='';for(let n=0;n<10000;n++,i++){const c=build(f,i);if(!c)break;k=norm(c.q)+'\u0000'+norm(c.a);if(!used.has(k)){out=c;break;}}idx[f]=i+1;if(!out)continue;const before={q:x.q,a:x.a};x.q=out.q;x.a=out.a;used.add(k);stats.changed_rows++;stats.by_family[f]=(stats.by_family[f]||0)+1;touched=true;if(stats.samples.length<120)stats.samples.push({id:x.id,family:f,before,after:{q:x.q,a:x.a}});}if(touched)stats.groups_touched++;}
const after=new Map();for(const x of rows){const a=after.get(key(x))||[];a.push(x);after.set(key(x),a);}const dup=[...after.values()].filter(a=>a.length>1);stats.duplicate_groups_after=dup.length;stats.duplicate_excess_after=dup.reduce((s,a)=>s+a.length-1,0);stats.groups_ge5_after=dup.filter(a=>a.length>=5).length;if(!stats.changed_rows)throw Error('no changes');if(stats.groups_ge5_after)throw Error('ge5 regression');const json=JSON.stringify(all);html=html.slice(0,m.index)+m[0].replace(m[1],json)+html.slice(m.index+m[0].length);fs.writeFileSync(HTML,html);fs.writeFileSync(OUT,JSON.stringify({generated_at:new Date().toISOString(),...stats},null,2)+'\n');console.log(JSON.stringify(stats,null,2));
