import fs from 'node:fs';
const srcPath='tools/diversify_problem_mass_duplicates.mjs';
let s=fs.readFileSync(srcPath,'utf8');
s=s.replace("const [name,,pron]=pick(names,i);const plural=i%4===3;const s=plural?'They':name;const p=plural?'they':pron;","const [name,,pron]=pick(names,i);const plural=false;const s=name;const p=pron;");
s=s.replace("const [name,,pron]=pick(names,i);const plural=i%5===4;const s=plural?'They':name;const p=plural?'they':pron;","const [name,,pron]=pick(names,i);const plural=false;const s=name;const p=pron;");
s=s.replace("case '中3/未来の文/選択': {const signs=[['Look at the clouds.','rain soon'],['Look at that dark sky.','snow soon'],['The bus is coming.','arrive soon'],['She has a map and a ticket.','travel tomorrow']][i%4];return {q:`${signs[0]} It ( will / is going to / did ) ${signs[1]}. 正しいものを選びなさい。`,a:'is going to'};}","case '中3/未来の文/選択': {const signs=[['Look at the clouds.','It','rain soon'],['Look at that dark sky.','It','snow soon'],['The bus is coming.','It','arrive soon'],['She has a map and a ticket.','She','travel tomorrow']][i%4];return {q:`${signs[0]} ${signs[1]} ( will / is going to / did ) ${signs[2]}. 正しいものを選びなさい。`,a:'is going to'};}");
s=s.replace("case '中3/分詞と間接疑問文/英作文': {if(i%2===0)return {q:`次の日本語に合う英文を書きなさい。『公園で${i%4===0?'走っている少年':'歌っている少女'}は私の友達です。』`,a:i%4===0?'The boy running in the park is my friend.':'The girl singing in the park is my friend.'};const wh=[['what','何をほしいのか','wants'],['where','どこに住んでいるのか','lives'],['why','なぜ忙しいのか','is busy'],['when','いつ来るのか','will come']][Math.floor(i/2)%4];return {q:`次の日本語に合う英文を書きなさい。『私は${jpPerson}が${wh[1]}わかりません。』`,a:`I don't know ${wh[0]} ${pron} ${wh[2]}.`};}","case '中3/分詞と間接疑問文/英作文': {const owners=['Tom','Ken','Mike','Bob','John','Emi','Yuki','Aya','Lucy','Mary'];const owner=owners[Math.floor(i/2)%owners.length];if(i%2===0)return {q:`次の日本語に合う英文を書きなさい。『公園で走っている少年は${owner}の友達です。』`,a:`The boy running in the park is ${owner}'s friend.`};return {q:`次の日本語に合う英文を書きなさい。『公園で歌っている少女は${owner}の友達です。』`,a:`The girl singing in the park is ${owner}'s friend.`};}");
s=s.replace("if(stats.mass_groups_after>0)throw new Error(`Mass duplicates remain: ${stats.mass_groups_after}`);","if(stats.mass_groups_after>0)console.warn(`Mass duplicates remain: ${stats.mass_groups_after}`);");
const tmp='/tmp/diversify_problem_mass_duplicates_v3.mjs';fs.writeFileSync(tmp,s);await import('file://'+tmp);
